import json
from flask import Flask, request

from helper.openai_api import generate_image, text_completion
from helper.telegram_api import sendMessage, sendPhoto


app = Flask(__name__)

@app.route('/')
def home():
    return 'OK', 200


@app.route('/telegram', methods = ['POST', 'GET'])
def telegram():
    try:
        data = request.get_json()
        message = data['message']
        query = message['text']
        sender_id = message['from']['id']

        '''
        the user query will be divided into 2 parts:
        one will be for text generation which will be prompted with /ask
        one will be for image generation which will be prompted with /img
        if the user did not begin the query with any of those, the user will be asked to c hoose from any of the two prefixes.
        '''
        '''
        /ask for text generation
        '''
        words = query.split(' ')
        if words[0] == '/ask':
            query = ' '.join(words[1:])
            response = text_completion(query)

            sendMessage(sender_id, response['response'])

            print(sender_id,'-> ' ,query)
            print(response['response'])

        elif words[0] == '/img':
            query = ' '.join(words[1:])
            response = generate_image(query)

            sendPhoto(sender_id, response['url'], 'Generated by OPENAI.')

            print(sender_id,'-> ' ,query)
            print(response['url'])

        else:
            sendMessage(sender_id, 'Pleae use /ask and /img commands before your messages' )

    except:
        pass
    finally:
        return 'OK', 200